services:
  postgres:
    image: postgres:17.5
    container_name: my-bank-postgres
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=my_bank
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  kafka:
    image: apache/kafka:4.0.0
    container_name: my-bank-kafka
    user: root
    environment:
      KAFKA_LOG_DIRS: /kafka/data
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    ports:
      - "9092:9092"
    volumes:
      - kafka-logs:/kafka/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.4.1
    container_name: my-bank-keycloak
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    command: start-dev
    ports:
      - "8080:8080"
    volumes:
      - keycloakdata:/opt/keycloak/data

  zipkin:
    image: openzipkin/zipkin:3.5
    container_name: my-bank-zipkin
    ports:
      - "9411:9411"

  prometheus:
    image: prom/prometheus:v3.9.1
    container_name: my-bank-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ~/.prometheus/my-bank-prometheus.yml:/etc/prometheus/prometheus.yml
      - ~/.prometheus/alerts/my-bank-rules.yml:/etc/prometheus/alerts/rules.yml

  alertmanager:
    image: prom/alertmanager:v0.30.1
    container_name: my-bank-alertmanager
    ports:
      - "9095:9093"
    volumes:
      - ~/.prometheus/alerts/my-bank-alertmanager.yml:/etc/alertmanager/alertmanager.yml
    depends_on:
      - prometheus

  grafana:
    image: grafana/grafana:12.3.1
    container_name: my-bank-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.2.4
    container_name: my-bank-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"

  logstash:
    image: docker.elastic.co/logstash/logstash:9.2.4
    container_name: my-bank-logstash
    volumes:
      - ~/.logstash/pipeline/:/usr/share/logstash/pipeline/
    depends_on:
      - kafka
      - elasticsearch

  my-bank-front:
    image: my-bank-front:latest
    container_name: my-bank-front
    ports:
      - "7979:8080"
    environment:
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI: ${KEYCLOAK_ISSUER_URI}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_ID: ${FRONT_KEYCLOAK_CLIENT_ID}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_SECRET: ${FRONT_KEYCLOAK_CLIENT_SECRET}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SERVICE_ACCOUNTS_URL: http://my-bank-accounts:8080
      SERVICE_CASH_URL: http://my-bank-cash:8080
      SERVICE_TRANSFER_URL: http://my-bank-transfer:8080
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
      LOGGING_KAFKA_TOPIC_NAME: my-bank-logs
    depends_on:
      - keycloak

  my-bank-accounts:
    image: my-bank-accounts:latest
    container_name: my-bank-accounts
    ports:
      - "8282:8080"
    environment:
      SPRING_LIQUIBASE_URL: jdbc:postgresql://postgres:5432/my_bank
      SPRING_LIQUIBASE_USER: ${DB_USERNAME}
      SPRING_LIQUIBASE_PASSWORD: ${DB_PASSWORD}
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/my_bank
      SPRING_R2DBC_USERNAME: ${DB_USERNAME}
      SPRING_R2DBC_PASSWORD: ${DB_PASSWORD}
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: ${KEYCLOAK_ISSUER_URI}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_NOTIFICATIONS_TOPIC_NAME: my-bank-notifications
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
      LOGGING_KAFKA_TOPIC_NAME: my-bank-logs
    depends_on:
      - postgres
      - keycloak
      - kafka

  my-bank-cash:
    image: my-bank-cash:latest
    container_name: my-bank-cash
    ports:
      - "8383:8080"
    environment:
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: ${KEYCLOAK_ISSUER_URI}
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI: ${KEYCLOAK_ISSUER_URI}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_ID: ${CASH_KEYCLOAK_CLIENT_ID}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_SECRET: ${CASH_KEYCLOAK_CLIENT_SECRET}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SERVICE_ACCOUNTS_URL: http://my-bank-accounts:8080
      KAFKA_NOTIFICATIONS_TOPIC_NAME: my-bank-notifications
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
      LOGGING_KAFKA_TOPIC_NAME: my-bank-logs
    depends_on:
      - keycloak
      - kafka

  my-bank-transfer:
    image: my-bank-transfer:latest
    container_name: my-bank-transfer
    ports:
      - "8484:8080"
    environment:
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: ${KEYCLOAK_ISSUER_URI}
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI: ${KEYCLOAK_ISSUER_URI}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_ID: ${TRANSFER_KEYCLOAK_CLIENT_ID}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_SECRET: ${TRANSFER_KEYCLOAK_CLIENT_SECRET}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SERVICE_ACCOUNTS_URL: http://my-bank-accounts:8080
      KAFKA_NOTIFICATIONS_TOPIC_NAME: my-bank-notifications
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
      LOGGING_KAFKA_TOPIC_NAME: my-bank-logs
    depends_on:
      - keycloak
      - kafka

  my-bank-notifications:
    image: my-bank-notifications:latest
    container_name: my-bank-notifications
    ports:
      - "8585:8080"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_NOTIFICATIONS_TOPIC_NAME: my-bank-notifications
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
      LOGGING_KAFKA_TOPIC_NAME: my-bank-logs
    depends_on:
      - keycloak
      - kafka

volumes:
  pgdata:
  kafka-logs:
  keycloakdata:
  grafana-data: