java-app:
  nameOverride: "my-bank-accounts"

  replicaCount: 1

  image:
    repository: my-bank-accounts
    pullPolicy: IfNotPresent
    tag: "latest"

  imagePullSecrets: []

  serviceAccount:
    create: false
    automount: true
    annotations: {}
    name: ""

  podAnnotations: {}
  podLabels: {}

  podSecurityContext: {}

  securityContext: {}

  service:
    type: ClusterIP
    port: 8080

  ingress:
    enabled: false
    className: ""
    annotations: {}
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []

  resources: {}

  autoscaling:
    enabled: false

  volumes: []

  volumeMounts: []

  nodeSelector: {}

  tolerations: []

  affinity: {}

  configmap:
    kafka:
      notifications:
        topic:
          name: "{{ .Values.global.kafka.notifications.topic.name }}"
    logging:
      kafka:
        topic:
          name: "{{ .Values.global.logging.kafka.topic.name }}"

  env:
    - name: KEYCLOAK_ISSUER_URI
      value: "{{ .Values.global.keycloak.issuerUri }}"
    - name: DB_HOST
      value: "{{ .Release.Name }}-postgresql"
    - name: DB_USERNAME
      secretKeyRef:
        name: my-bank-secret
        key: accounts.db.username
    - name: DB_PASSWORD
      secretKeyRef:
        name: my-bank-secret
        key: accounts.db.password
    - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
      value: "{{ .Values.global.kafka.bootstrapServers }}"
    - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
      value: "{{ .Values.global.zipkin.tracing.endpoint }}"