apiVersion: v2
name: my-bank
description: Umbrella chart for My Bank application microservices. Orchestrates microservices and infrastructure via sub-charts
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: keycloak
    version: "25.2.0"
    repository: "oci://registry-1.docker.io/bitnamicharts"