apiVersion: v2
name: my-bank
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: keycloak
    version: "25.2.0"
    repository: "oci://registry-1.docker.io/bitnamicharts"