global:
  image:
    registry: ""
    tag: "latest"
  keycloak:
    issuerUri: http://{{ .Release.Name }}-keycloak/realms/master
  kafka:
    bootstrapServers: "{{ .Release.Name }}-kafka:9092"
    notifications:
      topic:
        name: "{{ .Release.Name }}-my-bank-notifications"
  zipkin:
    tracing:
      endpoint: http://{{ .Release.Name }}-zipkin:9411/api/v2/spans

kafka:
  image:
    repository: bitnamilegacy/kafka
  controller:
    replicaCount: 1
  listeners:
    client:
      protocol: PLAINTEXT
    controller:
      protocol: PLAINTEXT
    interbroker:
      protocol: PLAINTEXT
    external:
      protocol: PLAINTEXT
  overrideConfiguration:
    transaction.state.log.replication.factor: "1"
    transaction.state.log.min.isr: "1"
    offsets.topic.replication.factor: "1"

keycloak:
  image:
    repository: bitnamilegacy/keycloak
  auth:
    adminUser: admin
    existingSecret: my-bank-secret
    passwordSecretKey: keycloak.admin.password
  postgresql:
    image:
      repository: bitnamilegacy/postgresql
    auth:
      existingSecret: my-bank-secret
      secretKeys:
        adminPasswordKey: db.admin.password         # пароль суперпользователя БД
        userPasswordKey: keycloak.db.user.password  # пароль юзера keycloak к БД

zipkin:
  image:
    repository: bitnamilegacy/zipkin
  storageType: mem
  cassandra:
    enabled: false

kube-prometheus-stack:
  kubernetesServiceMonitors:
    enabled: false
  kubeStateMetrics:
    enabled: false
  nodeExporter:
    enabled: false
  prometheusOperator:
    serviceMonitor:
      selfMonitor: false
  prometheus:
    serviceMonitor:
      selfMonitor: false
  grafana:
    serviceMonitor:
      enabled: false
    defaultDashboardsEnabled: false
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: 'default'
            orgId: 1
            folder: ''
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default
    dashboards:
      default:
        jvm-micrometer-dashboard:
          url: https://grafana.com/api/dashboards/4701/revisions/10/download
          datasource:
            - name: DS_PROMETHEUS
              value: Prometheus
        spring-boot-observability-dashboard:
          url: https://grafana.com/api/dashboards/17175/revisions/2/download
          datasource:
            - name: DS_PROMETHEUS
              value: Prometheus
  alertmanager:
    serviceMonitor:
      selfMonitor: false

ingress:
  hosts:
    - host: "{{ .Release.Name }}-keycloak"
      paths:
        - path: /
          pathType: ImplementationSpecific
          backendServiceName: "{{ .Release.Name }}-keycloak"
    - host: "{{ .Release.Name }}-my-bank-front"
      paths:
        - path: /
          pathType: ImplementationSpecific
          backendServiceName: "{{ .Release.Name }}-my-bank-front"
    - host: "{{ .Release.Name }}-zipkin"
      paths:
        - path: /
          pathType: ImplementationSpecific
          backendServiceName: "{{ .Release.Name }}-zipkin"
    - host: "{{ .Release.Name }}-prometheus"
      paths:
        - path: /
          pathType: ImplementationSpecific
          backendServiceName: "{{ .Release.Name }}-kube-prometheus-stack-prometheus"
    - host: "{{ .Release.Name }}-grafana"
      paths:
        - path: /
          pathType: ImplementationSpecific
          backendServiceName: "{{ .Release.Name }}-grafana"